New resource for payment
senthilkumar2015/RESTAPI pull request #3
Opened 2017-05-19 11:43 UTC by thandugp

Payments endpoint allows you to make a Payment anonymously or by logging in. Responses will be returned in JSON format only.

2017-05-19 13:26 UTC, praveen3450 requested changes
Please make these documents readable. Please check with Jaffer/Surya/Gulsan working for UKB. They can give you a sample ".md" file and you can build on that.

2017-05-22 06:33 UTC, leelac commented on payments.md
> +## Payment collection [/BusinessPayments]
Is /BusinessPayments your endpoint or it is /payments?

2017-05-22 06:38 UTC, leelac commented on payments.md
> +| cardId | String | `Manadatory` | `Returned always` | It is the Identifier for the card that is saved in memcache. |
Is `card` a different resource? If yes then this property name can be replaced with resource name.

2017-05-22 06:42 UTC, leelac commented on payments.md
> +| cards | BusinessCards |`Optional` | `Returned always` | It is the BusinessCards endpoint which is cinvoked before payment resource to save the save or store in memcache to make the payment. [Busine
As card identifier is already provided, no need to provide the card details again. You can get the card details based on the card id.

2017-05-22 08:41 UTC, thandugp commented on payments.md
> +## Payment collection [/BusinessPayments]
Endpoint changed from /BusinessPayments to /payments as discussed.

2017-05-22 08:42 UTC, thandugp commented on payments.md
> +| cardId | String | `Manadatory` | `Returned always` | It is the Identifier for the card that is saved in memcache. |
yes, Card is a different resource and the property name is provided as resource name.

2017-05-22 11:54 UTC, praveen3450 reviewed
My initial set of comments of the payments resource. Please make the changes and get back once done.

2017-05-22 11:54 UTC, praveen3450 commented on payments.md
> +### Request (application/json)
In UKB we follow vendor specific content type - Request (application/vnd.api+json)

2017-05-22 11:54 UTC, praveen3450 commented on payments.md
> +  {
As per jsonapi standards a json should adhere to standards. A sample representation is given below.

{
  "data": {
    "type": "quotes",
    "attributes": {
      "fuel": "gas",
      "contract-start-date": "03/02/2017",
      "customer-details": {
        "title": "Mr",
        "first-name": "Fred"
      },
      "sites": [
        "1213456789"
      ]
    }
  }
}

2017-05-22 11:54 UTC, praveen3450 commented on payments.md
> +### Response 200 (application/json) - successful payment
Response also follows vendor specific jsonapi standards. "(application/vnd.api+json)"

2017-05-22 11:54 UTC, praveen3450 commented on payments.md
> +```json
All responses should adhere to json api standards. A representation is given for your reference.
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "id": "300652148",
    "type": "quotes",
    "attributes": {
      "fuel": "gas",
      "customer-details": {
        "title": "Mr",
        "first-name": "Fred",
      },
      "contract-start-date": "27/03/2017",
      "sites": [
        {
          "contract-account-number": "000602106178",
          "site-address": "237 KINGSTON ROAD TEDDINGTON TW11 9JJ GB",
        }
      ]
    }
  }
}

2017-05-22 11:54 UTC, praveen3450 commented on payments.md
> +| card | String | `Manadatory` | `Returned always` | It is the card identifier used for making payment. |
Please elobrate if this attribute is related to payment via saved card.

2017-05-22 11:54 UTC, praveen3450 commented on payments.md
> +| contractAccount | String | `Returned always` | It is the account for which the customer is making a payment. |
No camel casing for attribute names. You can use something like contract-account-number.

2017-05-22 11:54 UTC, praveen3450 commented on payments.md
> +### BusinessPayment
How can i use this resource and its attributes for making payment with the following scenarios. 
a) Payment with a saved card.
b) Payment using a new card.
c) Payment using anonymous customer.
d) Payment using a logged in customer.

This resource doesn't adhere to all the above scenarios. Please rework.

2017-05-24 11:08 UTC, praveen3450 reviewed
Please check the review comments and update the doc...

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
> +| contract-account | String | `Mandatory` | `Returned always` | It is the account for which the customer is making a payment. |
Please change it to contact-account-number to maintain consistency.

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
> +| card | String | `Manadatory` | `Returned always` | It is the card identifier which is either saved in SAP or saved in memcache in case of payment using saved card or payment using new card details
This will be an encrypted string due to the client side encryption that will be done by front end ember.
Rename it to something like card-details.

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
>  `Note`: When the error code returned from the SAP for payment failure status is either of DCCARD_1 ... DCCARD_16 values error code 500 will be returned from the endpoint.
A 500 or 5XX error can be used only when the server is unavailable/timeout/not reachable...etc. All other world pay errors will likely fall under 400 or 4XX client errors. Please remove reference to payware errors (DDCARD_1....etc)

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
>  	cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526
Why do we need a CID? Does that have any significance or does it provide any security?

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
> +		"card": "42563574674",
Please use a long encrypted string from worldpay docs.

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
> +		"contractAccount": "600134652"
Please change the sample value to 600123456

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
>          "status": "SUCCESS",
Why do we need the attribute "status" for a 200 OK success response.

2017-05-24 11:08 UTC, praveen3450 commented on payments.md
>  		"contractAccount": "600134652",
Please change to contract-account-number and update the sample value as 600123456.
Also update card to card-details and updated sample value as an encrypted string.

2017-05-26 06:50 UTC, merged