Card detail resource
senthilkumar2015/RESTAPI pull request #6
Opened 2017-05-19 12:49 UTC by Anburajap

Cards endpoint allows you to manage card Details

2017-05-19 13:24 UTC, praveen3450 requested changes
Please make these documents readable. Please check with Jaffer/Surya/Gulsan working for UKB. They can give you a sample ".md" file and you can build on that.

2017-05-25 08:21 UTC, Priya1803 requested changes

2017-05-25 08:21 UTC, Priya1803 commented on Card details.md
> +|priorityCard|String| Optional | Returned always| It contains the priority flag of that particular customer. Value may be 'Y' or 'N'|
If the attribute can hold only 2 possible values, this can be be declared as `boolean` instead of `Y` and `N`

2017-05-25 08:21 UTC, Priya1803 commented on Card details.md
> +| holderName|String | Optional | Returned always | Its helps to identify the name of the card holder.|
All the fields are given as optional for `As Request`. Can we validate this, we would need at least some fields for POST operation.

2017-05-25 08:21 UTC, Priya1803 commented on Card details.md
> +|saveCardID|String | Optional | Returned always| It contains the unique id for each card.|
If the value in `saveCardId` is unique for each card, the same can be used as `id` for the resource, instead of generating a random value for `id`.

2017-05-25 08:21 UTC, Priya1803 commented on Card details.md
> +
Can we add possible error validations for all operations? For e.g. What if the requested `id` is not found or invalid.

2017-05-25 08:21 UTC, Priya1803 commented on Card details.md
> +|cardType|String  | Optional | Returned always| It contains the type of card like Visa,Maestro.|
Can we add all expected description from front-end for `cardType`?

2017-05-25 08:21 UTC, Priya1803 commented on Card details.md
> +    + id: 00505683065B1EE78EF34A3F0BD0AF4C (string) - SaveCardId
Is `PUT` applicable only for anonymous customer? If no can we add access token in the headers too?

2017-05-26 06:49 UTC, closed without merging

2017-06-07 06:49 UTC, Anburajap commented on Card details.md
> +| holderName|String | Optional | Returned always | Its helps to identify the name of the card holder.|
Validated

2017-06-07 06:49 UTC, Anburajap commented on Card details.md
> +|cardType|String  | Optional | Returned always| It contains the type of card like Visa,Maestro.|
CardType provided

2017-06-07 06:49 UTC, Anburajap commented on Card details.md
> +|saveCardID|String | Optional | Returned always| It contains the unique id for each card.|
saveCardId made as unique ID.

2017-06-07 06:50 UTC, Anburajap commented on Card details.md
> +|priorityCard|String| Optional | Returned always| It contains the priority flag of that particular customer. Value may be 'Y' or 'N'|
priorityCard made as boolean

2017-06-07 06:50 UTC, Anburajap commented on Card details.md
> +    + id: 00505683065B1EE78EF34A3F0BD0AF4C (string) - SaveCardId
cid value added